# Generated by Django 4.2.1 on 2023-05-23 14:58

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_openinghours_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOpeningHours',
            fields=[
                ('dayOfWeek', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]), default=list, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
