# Generated by Django 4.2.1 on 2023-05-23 16:23

from django.db import migrations
import reservations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_dayopeninghours_delete_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayopeninghours',
            name='hours',
            field=reservations.fields.IntegerListField(),
        ),
    ]
