# Generated by Django 4.2.1 on 2023-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_dayopeninghours_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayopeninghours',
            name='dayOfWeek',
            field=models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], primary_key=True, serialize=False),
        ),
    ]
