# Generated by Django 4.2.1 on 2023-05-24 07:42

from django.db import migrations, models
import reservations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_dayopeninghours_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalGymDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('hours', reservations.fields.IntegerListField()),
                ('capacity', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='GymDay',
            fields=[
                ('dayOfWeek', models.IntegerField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], primary_key=True, serialize=False)),
                ('hours', reservations.fields.IntegerListField()),
                ('capacity', models.IntegerField(default=30)),
            ],
        ),
        migrations.DeleteModel(
            name='DayOpeningHours',
        ),
        migrations.DeleteModel(
            name='ExceptionalClosingHours',
        ),
        migrations.DeleteModel(
            name='ExceptionalOpeningHours',
        ),
    ]
