# Generated by Django 4.2.1 on 2023-05-24 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_exceptionalgymday_gymday_delete_dayopeninghours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hours',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
