# Generated by Django 4.2.1 on 2023-05-24 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_reservation_hours_reservation_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
